export const INGESTION_PIPELINE_PORT = Symbol("INGESTION_PIPELINE_PORT");
export const PROFILE_REGISTRY = Symbol("PROFILE_REGISTRY");
export const PARSER_REGISTRY_TOKEN = Symbol("PARSER_REGISTRY_TOKEN");
export const CHUNKER_REGISTRY_TOKEN = Symbol("CHUNKER_REGISTRY_TOKEN");
export const NORMALIZER_REGISTRY_TOKEN = Symbol("NORMALIZER_REGISTRY_TOKEN");
